# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
 demands:
 - visualstudio

stages:
  - stage:
    jobs:
    - job: Build
      steps:
      - task: NuGetToolInstaller@0
        inputs:
          checkLatest: true
      
      - task: NuGetRestore@1
        inputs:
         solution: '**\*.sln'

      - task: MSBuild@1
        inputs:
         clean: true
         platform: 'any cpu'
         configuration: 'release'
         solution: '**\*.sln'
         msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package 
 /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
